sudo: required
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.18.0
branches:
  only:
  - master
  - develop
  - "/^(hotfix).*$/"
  - "/^(feature).*$/"
language: node_js
node_js:
- '9'
before_install:
# heroku cli install
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
# login to docker registries (dockerhub + heroku) 
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
- npm --cwd bookapp/ install
script:
- npm -cwd bookapp/ test
- npm --cwd bookapp/ run build
- docker build -t app .
